### ISSUE TITLE
The exclude and include strings must not be the same (5.0)

### ISSUE THREAD

**Issue by Ionshard** [franc6/ics_calendar#149]
Attempting to setup my calendar from scratch.

I get the following error when I attempt to add the exclude filter of "OOO"

![Screenshot_20240910-220930.png](https://github.com/user-attachments/assets/8c9302e6-0d67-4ab6-81cf-14a28ad34431)

I am not setting any include filter

**Comment by ingoratsdorf** [comment]
Same here when trying to reinstate the calendars that are not imported any more after the integration told me to removed the yaml config. Cannot re-add, does not display. Had to add yaml config again.

**Comment by franc6** [comment]
Fixed in 5.0.1

**Comment by EagleStClair** [comment]
> Fixed in 5.0.1

I leave include and exclude filters blank/empty but still get the same error message in 5.0.1

**Comment by franc6** [comment]
It's an easy fix.  I'll get to it as soon as I can...

**Comment by franc6** [comment]
Fixed in 5.0.2
